/*
 * This file was automatically generated by EvoSuite
 */

package com.lts;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.lts.ExceptionUtil;
import java.io.PrintWriter;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ExceptionUtilEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Object[] objectArray0 = ExceptionUtil.toData((Object) null);
      assertNotNull(objectArray0);
  }

  @Test
  public void test1()  throws Throwable  {
      Object[] objectArray0 = ExceptionUtil.toData((Object) null, (Object) null, (Object) null);
      assertNotNull(objectArray0);
  }

  @Test
  public void test2()  throws Throwable  {
      ExceptionUtil exceptionUtil0 = new ExceptionUtil();
      assertNotNull(exceptionUtil0);
  }

  @Test
  public void test3()  throws Throwable  {
      Object[] objectArray0 = ExceptionUtil.toData((Object) null, (Object) null);
      assertNotNull(objectArray0);
  }

  @Test
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try {
        ExceptionUtil.createStackTrace((Throwable) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try {
        ExceptionUtil.createStackTrace((PrintWriter) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test6()  throws Throwable  {
      Object[] objectArray0 = ExceptionUtil.toData((Object) null, (Object) null, (Object) null, (Object) null);
      assertNotNull(objectArray0);
  }

  @Test
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try {
        ExceptionUtil.toSummaryMessage((Throwable) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
